name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
